AppCalculadora/urls.py
from django.urls import path
from AppCalculadora.views import home
from . import views 

urlpatterns = [
    path('', views.home, name='home'), 
    
    
    # Módulo de Empresa
    path('listarempresa/', views.listar_empresa, name='listarEmpresa'),
    path('cadastrarempresa/', views.cadastrar_empresa, name='cadastrarEmpresa'),
    path('editarempresa/<int:pk>/', views.editar_empresa, name='editarEmpresa'),
    path('excluirempresa/<int:pk>/', views.excluir_empresa, name='excluirEmpresa'),
    
    # Módulo Tipo de Recurso
    path('listartiporecurso/', views.listar_tipo_recurso, name='listarTipoRecurso'),
    path('cadastrartiporecurso/', views.cadastrar_tipo_recurso, name='cadastrarTipoRecurso'),
    path('editartiporecurso/<int:pk>/', views.editar_tipo_recurso, name='editarTipoRecurso'),
    path('excluirtiporecurso/<int:pk>/', views.excluir_tipo_recurso, name='excluirTipoRecurso'),

    # Módulo Recurso
    path('listarrecurso/', views.listar_recurso, name='listarRecurso'),
    path('cadastrarrecurso/', views.cadastrar_recurso, name='cadastrarRecurso'),
    path('editarrecurso/<int:pk>/', views.editar_recurso, name='editarRecurso'),
    path('excluirrecurso/<int:pk>/', views.excluir_recurso, name='excluirRecurso'),

    
   # Módulo Tipo de Custo
    path('listartipocusto/', views.listar_tipo_custo, name='listarTipoCusto'),
    path('cadastrartipocusto/', views.cadastrar_tipo_custo, name='cadastrarTipoCusto'),
    path('editartipocusto/<int:pk>/', views.editar_tipo_custo, name='editarTipoCusto'),
    path('excluirtipocusto/<int:pk>/', views.excluir_tipo_custo, name='excluirTipoCusto'),
    
    # Módulo Função de Custo

    path('listarfuncaodecusto/', views.listar_funcao_custo, name='listarFuncaoCusto'),
    path('cadastrarfuncaodecusto/', views.cadastrar_funcao_custo, name='cadastrarFuncaoCusto'),
    path('editarfuncaodecusto/<int:pk>/', views.editar_funcao_custo, name='editarFuncaoCusto'),
    path('excluirfuncaodecusto/<int:pk>/', views.excluir_funcao_custo, name='excluirFuncaoCusto'),

    # Módulo Comportamento de Custo
    path('listarcomportamentocusto/', views.listar_comportamento_custo, name='listarComportamentoCusto'),
    path('cadastrarcomportamentocusto/', views.cadastrar_comportamento_custo, name='cadastrarComportamentoCusto'),
    path('editarcomportamentocusto/<int:pk>/', views.editar_comportamento_custo, name='editarComportamentoCusto'),
    path('excluircomportamentocusto/<int:pk>/', views.excluir_comportamento_custo, name='excluirComportamentoCusto'),

    # Módulo Custo
    path('listarcusto/', views.listar_custo, name='listarCusto'),
    path('cadastrarcusto/', views.cadastrar_custo, name='cadastrarCusto'),
    path('editarcusto/<int:pk>/', views.editar_custo, name='editarCusto'),
    path('excluircusto/<int:pk>/', views.excluir_custo, name='excluirCusto'), 

    # Módulo Empresa Custo   
    path('cadastrarempresacusto/', views.cadastrar_empresa_custo, name='cadastrarEmpresaCusto'),
    path('listarempresacusto/', views.listar_empresa_custo, name='listarEmpresaCusto'),
    path('editarempresacusto/<int:pk>/', views.editar_empresa_custo, name='editarEmpresaCusto'),
    path('excluirempresacusto/<int:pk>/', views.excluir_empresa_custo, name='excluirEmpresaCusto'),

    # Módulo Calculo do Custo
    path('calcularcusto/', views.calcular_custo_datacenter, name='calcularCustoDatacenter'),
    #
    path('calcularpreco/', views.calcular_preco, name='calcularPreco'),
    path('listarcalcularcusto/', views.listar_calcular_custo, name='listarCalcularCusto'),
    # Outras URLs
    
    # Passo 2 Cadastrar recurso datacenter
    path('listarecursodatacenter/', views.listar_recurso_datacenter, name='listarRecursoDatacenter'),
    path('cadastrarrecursodatacenter/', views.cadastrar_recurso_datacenter, name='cadastrarRecursoDatacenter'),
    path('editarrecursodatacenter/<int:pk>/', views.editar_recurso_datacenter, name='editarRecursoDatacenter'),
    path('excluirrecursodatacenter/<int:pk>/', views.excluir_recurso_datacenter, name='excluirRecursoDatacenter'), 

     # Módulo Servico
    path('listarservico/', views.listar_servico, name='listarServico'),
    path('cadastrarservico/', views.cadastrar_servico, name='cadastrarServico'),
    path('editarservico/<int:pk>/', views.editar_servico, name='editarServico'),
    path('excluirservico/<int:pk>/', views.excluir_servico, name='excluirServico'),    


    # Passo 4 ServicoRecurso    
    path('listarservicorecurso', views.listar_servico_recurso, name='listarServicoRecurso'),
    path('cadastrarservicorecurso/', views.cadastrar_servico_recurso, name='cadastrarServicoRecurso'),
    path('editarservicorecurso/<int:id>/', views.editar_servico_recurso, name='editarServicoRecurso'),
    path('excluirservicorecurso/<int:id>/', views.excluir_servico_recurso, name='excluirServicoRecurso'),

    # Passo 5 ModeloAssinatura
    path('cadastrarmodeloassinatura', views.cadastrar_modelo_assinatura, name='cadastrarModeloAssinatura'),
    path('listarmodeloassinatura/', views.listar_modelo_assinatura, name='listarModeloAssinatura'),
    path('editarmodeloassinatura/<int:pk>/', views.editar_modelo_assinatura, name='editarModeloAssinatura'),
    path('excluirmodeloassinatura/<int:pk>/', views.excluir_modelo_assinatura, name='excluirModeloAssinatura'),

    path('getvalorunitario/', views.get_valor_unitario, name='getValorunitario'),
    path('getservicos/', views.get_servicos, name='getServicos'),    
    path('getmetodospagamento/', views.get_metodos_pagamento, name='getMetodosPagamento'),        

    path('getdashboard/', views.get_dashboard, name='getDashboard'),
    # outras URLs...
    
]

    

calculadora/urls.py
from django.contrib import admin
from django.urls import include, path
from AppCalculadora import views
urlpatterns = [
    path('', include('AppCalculadora.urls')),  # Aqui estamos incluindo novamente para a rota raiz    
    path('AppCalculadora/', include('AppCalculadora.urls')),  
    path('admin/', admin.site.urls),
    
]

AppCalculadora/models.py
from decimal import Decimal, InvalidOperation
from django.db import models

# Create your models here.
from django.db import models
import datetime

class Empresa(models.Model):
    nome = models.CharField(max_length=255)
    endereco = models.CharField(max_length=255)
    telefone = models.CharField(max_length=20)
    email = models.EmailField(max_length=255)
    website = models.CharField(max_length=255)

    def __str__(self):
        return self.nome
    

class TipoRecurso(models.Model):
    nome = models.CharField(max_length=255)
    def __str__(self):
        return self.nome

class Recurso(models.Model):
        
    UNIDADE_MEDIDA_CHOICES = [
        ('núcleos de CPU', 'núcleos de CPU'),
        ('em gigabytes (GB)', 'em gigabytes (GB) '),
        ('em gigabytes (GB) Transferidos', 'em gigabytes (GB) Transferidos'),
        ('eventos monitorados', 'eventos monitorados'),        
    ]
    tipo_recurso = models.ForeignKey(TipoRecurso, on_delete=models.CASCADE)
    descricao = models.CharField(max_length=255)
    detalhes = models.TextField()
    unidade_medida = models.CharField(
        max_length=255,
        choices=UNIDADE_MEDIDA_CHOICES,
        default='núcleos de CPU',
    )

    def __str__(self):
        return f'{self.tipo_recurso} - {self.descricao}'

        

class Servico(models.Model):
    IAAS = 'IAAS'
    PAAS = 'PAAS'
    SAAS = 'SAAS'
    
    MODELO_CHOICES = [
        (IAAS, 'Infrastructure as a Service (IAAS)'),
        (PAAS, 'Platform as a Service (PAAS)'),
        (SAAS, 'Software as a Service (SAAS)'),
    ]
    
    modelo = models.CharField(
        max_length=255,
        choices=MODELO_CHOICES,
        default=IAAS,
    )
    nome = models.CharField(max_length=255)
    descricao = models.TextField()
    
    def __str__(self):
        return self.nome

class ServicoAgrupado(models.Model):
    IAAS = 'IAAS'
    PAAS = 'PAAS'
    SAAS = 'SAAS'
    
    MODELO_CHOICES = [
        (IAAS, 'Infrastructure as a Service (IAAS)'),
        (PAAS, 'Platform as a Service (PAAS)'),
        (SAAS, 'Software as a Service (SAAS)'),
    ]
    
    modelo = models.CharField(
        max_length=255,
        choices=MODELO_CHOICES,
        default=IAAS,
    )
    nome = models.CharField(max_length=255)
    descricao = models.TextField()
    
    def __str__(self):
        return self.nome



class ServicoRecurso(models.Model):
    servico = models.ForeignKey(Servico, on_delete=models.CASCADE)
    recurso = models.ForeignKey(Recurso, on_delete=models.CASCADE)
    quantidade = models.DecimalField(max_digits=10, decimal_places=2)   
    detalhe = models.CharField(max_length=80, default="Nada a informar")

    def __str__(self):
        return f'{self.servico.nome} usa {self.quantidade} {self.recurso.descricao}'
    

class TipoCusto(models.Model):
    nome = models.CharField(max_length=255, help_text="Nome do tipo de custo (ex: Pessoal, Energia, Licenças)")
    descricao = models.TextField(help_text="Descrição do tipo de custo")

    def __str__(self):
        return self.nome

class FuncaoCusto(models.Model):
    nome = models.CharField(max_length=255)
    exemplos = models.TextField()

    def __str__(self):
        return self.nome

class ComportamentoCusto(models.Model):
    nome = models.CharField(max_length=255)
    exemplos = models.TextField()

    def __str__(self):
        return self.nome

class Custo(models.Model):
    descricao = models.CharField(max_length=255)
    tipo_custo = models.ForeignKey(TipoCusto, on_delete=models.CASCADE, related_name="custos", default=1)
    funcao_custo = models.ForeignKey(FuncaoCusto, on_delete=models.CASCADE, related_name="custos", default=1)
    comportamento_custo = models.ForeignKey(ComportamentoCusto, on_delete=models.CASCADE, related_name="custos", default=1)  # assumindo que existe um ComportamentoCusto com ID 1

    def __str__(self):
        return f"{self.descricao}"

class EmpresaCusto(models.Model):
    empresa = models.ForeignKey(Empresa, on_delete=models.RESTRICT, related_name="empresa_custos")
    custo = models.ForeignKey(Custo, on_delete=models.RESTRICT)
    valor = models.DecimalField(max_digits=12, decimal_places=2) 
    periodicidade = models.CharField(default="anual", max_length=255, choices=[('mensal', 'Mensal'), ('anual', 'Anual')])
    data_inicio = models.DateField(default=datetime.date.today)
    data_fim = models.DateField(null=True, blank=True)

    def __str__(self):
       return f"{self.empresa.nome} - {self.custo}"



class CustoDataCenter(models.Model):
    REGION_CHOICES = [
        ('DataCenter1', 'Data Center Sefin'),
        ('DataCenter2', 'Data Center Sepog'),
    ]
    
    VM_TYPE_CHOICES = [
        ('standard_b1s', 'Standard B1s'),
        ('standard_d2s_v3', 'Standard D2s v3'),
        # Adicione outros tipos de VM aqui
    ]
    
    OS_CHOICES = [
        ('linux', 'Linux'),
        ('windows', 'Windows'),
    ]
    
    STORAGE_TYPE_CHOICES = [
        ('standard_hdd', 'Standard HDD'),
        ('premium_ssd', 'Premium SSD'),
    ]
    
    IP_TYPE_CHOICES = [
        ('dynamic', 'Dynamic IP'),
        ('static', 'Static IP'),
    ]

    region = models.CharField(max_length=50, choices=REGION_CHOICES)
    vm_type = models.CharField(max_length=50, choices=VM_TYPE_CHOICES)
    num_vms = models.IntegerField()
    os = models.CharField(max_length=50, choices=OS_CHOICES)
    storage_type = models.CharField(max_length=50, choices=STORAGE_TYPE_CHOICES)
    disk_size = models.CharField(max_length=50)
    num_disks = models.IntegerField()
    num_ips = models.IntegerField()
    ip_type = models.CharField(max_length=50, choices=IP_TYPE_CHOICES)
    hours_per_month = models.IntegerField()
    total_cost = models.DecimalField(max_digits=10, decimal_places=2)

    def __str__(self):
        return f"{self.vm_type} - {self.region} - {self.total_cost}"



# 2 Passo da metodologia

    
class RecursoDataCenter(models.Model):
    empresa = models.ForeignKey('Empresa', on_delete=models.CASCADE, related_name='Empresa', null=True, blank=True, default=None)
    recurso = models.ForeignKey('Recurso', on_delete=models.CASCADE, related_name='Recurso', null=True, blank=True, default=None)    
    valor = models.DecimalField(max_digits=12, decimal_places=2, verbose_name="Valor Anual", default=0.00)
    detalhe = models.CharField(max_length=255, verbose_name="Unidade de Medida")
    percentual_finops = models.DecimalField(max_digits=5, decimal_places=2, default=0.00)
    custo_total_aplicado = models.DecimalField(max_digits=12, decimal_places=2, default=0.00)
    valor_unitario = models.DecimalField(max_digits=12, decimal_places=2, default=0.00)
    def save(self, *args, **kwargs):
        try:
            # Calcular o somatório do campo valor para todos os registros da mesma empresa
            total_valor = EmpresaCusto.objects.filter(empresa=self.empresa).aggregate(total=models.Sum('valor'))['total'] or Decimal('0.00')
            
            # Certificar que total_valor e percentual_finops são do tipo Decimal
            total_valor = Decimal(total_valor)
            percentual_finops = Decimal(self.percentual_finops)
            custo_total = (total_valor * percentual_finops)/100
            # Calcular o custo_total_aplicado e unitário
            self.custo_total_aplicado = custo_total
            self.valor_unitario = (custo_total / self.valor)
        except InvalidOperation:
            # Tratar a exceção de operação inválida
            self.custo_total_aplicado = Decimal('0.00')
        
        # Chamar o método save original
        super(RecursoDataCenter, self).save(*args, **kwargs)
    
    def __str__(self):
        return f"{self.empresa.nome} -  {self.valor} - {self.detalhe}"
    
# 5 Modelo de assinatura
class ModeloAssinatura(models.Model):
    nome = models.CharField(max_length=255)
    descricao = models.CharField(max_length=255)    
    valor_desconto = models.DecimalField(max_digits=5, decimal_places=2, verbose_name="Valor Anual", default=0.00)   

    def __str__(self):
        return f"{self.nome} - {self.valor_desconto}"   

        

AppCalculadora/templates/ModeloAssinatura/cadastrar_modelo_assinatura.html
{% extends 'base.html' %}

{% load form_tags %}

{% block content %}
<div class="container mt-4">
    <h1 class="page-title">Cadastrar Novo Modelo de Assinatura</h1>
    <form method="post" class="mt-4">
        {% csrf_token %}
        <div class="mb-3">
            <label for="id_nome" class="form-label">Nome</label>
            {{ form.nome|add_class:"form-control" }}
        </div>
        <div class="mb-3">
            <label for="id_descricao" class="form-label">Descrição</label>
            {{ form.descricao|add_class:"form-control" }}
        </div>
        <div class="mb-3">
            <label for="id_valor_desconto" class="form-label">Valor Desconto (%)</label>
            {{ form.valor_desconto|add_class:"form-control" }}
        </div>
        <div class="d-flex justify-content-between">
            <a href="{% url 'listarModeloAssinatura' %}" class="btn btn-secondary">Voltar</a>
            <button type="submit" class="btn btn-primary">Cadastrar</button>
        </div>
    </form>
</div>
{% endblock %}

AppCalculadora/templates/ModeloAssinatura/editar_modelo_assinatura.html
{% extends 'base.html' %}

{% load form_tags %}

{% block content %}
<div class="container mt-4">
    <h1 class="page-title">Editar Modelo de Assinatura</h1>
    <form method="post" class="mt-4">
        {% csrf_token %}
        <div class="mb-3">
            <label for="id_nome" class="form-label">Nome</label>
            {{ form.nome|add_class:"form-control" }}
        </div>
        <div class="mb-3">
            <label for="id_descricao" class="form-label">Descrição</label>
            {{ form.descricao|add_class:"form-control" }}
        </div>
        <div class="mb-3">
            <label for="id_valor_desconto" class="form-label">Valor Desconto (%)</label>
            {{ form.valor_desconto|add_class:"form-control" }}
        </div>
        <div class="d-flex justify-content-between">
            <a href="{% url 'listarModeloAssinatura' %}" class="btn btn-secondary">Voltar</a>
            <button type="submit" class="btn btn-primary">Salvar</button>
        </div>
    </form>
</div>
{% endblock %}

AppCalculadora/templates/ModeloAssinatura/excluir_modelo_assinatura.html
{% extends "base.html" %}

{% block content %}
<div class="container mt-4">
    <h2>Excluir Modelo de Assinatura</h2>
    <p>Tem certeza de que deseja excluir o modelo de assinatura "{{ modelo.nome }}"?</p>
    <form method="post">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger">Excluir</button>
        <a href="{% url 'listarModeloAssinatura' %}" class="btn btn-secondary">Cancelar</a>
    </form>
</div>
{% endblock %}

AppCalculadora/templates/ModeloAssinatura/listar_modelo_assinatura.html
{% extends "base.html" %}

{% block content %}
<div class="container mt-4">
    <h2>Lista de Tipos de pagamento</h2>
    <table class="table table-striped">
        <thead>
            <tr>
                <th>Nome</th>
                <th>Descrição</th>
                <th>Valor Desconto (%)</th>
                <th>Ações</th>
            </tr>
        </thead>
        <tbody>
            {% for modelo in modelos %}
            <tr>
                <td>{{ modelo.nome }}</td>
                <td>{{ modelo.descricao }}</td>
                <td>{{ modelo.valor_desconto }}</td>

                <td>
                    <a href="{% url 'editarModeloAssinatura' modelo.id %}" class="btn btn-primary btn-sm">Editar</a>
                </td>    
                <td>                    
                    <a href="{% url 'excluirModeloAssinatura' modelo.id %}" class="btn btn-danger btn-sm">Excluir</a>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    <br>
    <a href="{% url 'cadastrarModeloAssinatura' %}" class="btn btn-primary mb-3">Adicionar Novo Modelo</a>
</div>
{% endblock %}